crudapp/urls.py
import re
from django.urls import re_path
from . import views

app_name='crudapp'

urlpatterns=[
    re_path(r'^$',views.index,name='index'),
    re_path(r'basic_form$',views.basic_forms,name='form'),
    re_path(r'model_form$',views.model_forms,name='model_form'),
    re_path(r'crud$',views.crud,name='crud'),   
    re_path(r'delete',views.delete,name='delete'),
    re_path(r'update',views.update1,name='update'),
]

simplecrud/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from crudapp import views

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'',include('crudapp.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns=[
        re_path(r'^__debug__/',include(debug_toolbar.urls))
    ]+urlpatterns
    

crudapp/models.py
from django.db import models

# Create your models here.
 
class info(models.Model):
    name=models.CharField(max_length=256,unique=True)
    age=models.IntegerField()
    gender=models.CharField(max_length=256)
    def __str__(self):
        return self.name

        

crudapp/forms.py
from django import forms
from django.core import validators
from .models import info
class basic_form(forms.Form):
    name=forms.CharField(max_length=256,required=True)
    age=forms.IntegerField(required=True)
    gender=forms.CharField(max_length=256,required=True)
    
    
class model_form(forms.ModelForm):
    class Meta:
        global CHOICES
        model=info
        fields='__all__'
        CHOICES = [('M','Male'),('F','Female')]
        widgets={'age':forms.NumberInput(),'gender':forms.RadioSelect(choices=CHOICES),'name':forms.TimeInput()}
        

class update(forms.Form):
    name = forms.CharField(max_length=255,required=False)
    age = forms.IntegerField(required=False)
    gender=forms.ChoiceField(choices=CHOICES,required=False)

crudapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from .forms import basic_form,model_form,update
from  . models import info

# Create your views here.

def index(request):
    context_dir={
        'request':request,
        'page':'This is the index page',
        'form':info.objects.all(),
    }
    return render(request, 'index.html', context=context_dir)
    
def basic_forms(request):
    form=basic_form()
    context_dir={
        'form':form,
        'request':request,
        'page':'This is the form page',
        'form1':info.objects.all(),
    }
    if request.method == 'POST':
        #Simple html form
        context_dir.update({'html_form_data':{'name':request.POST.get('name'),'age':request.POST.get('age'),'gender':request.POST.get('gender')}})
        
        #Django form
        form=basic_form(request.POST)    
        if form.is_valid():
            #get form's data at once
            all_data=form.cleaned_data
            context_dir.update({'all_data':all_data})
            #get form data one by one
            form_details={'form_details':{'name':form.cleaned_data['name'],'age':form.cleaned_data['age'],'gender':form.cleaned_data['gender']}}
            context_dir.update(form_details)
            
        else:
            print("Form is not valid")
    return render(request, 'basic_form.html', context=context_dir)


def model_forms(request):
    modelform=model_form()
    
    context_dir={
        'modelform':modelform,
        'form':info.objects.all(),
        'request':request,
        'page':'This is the model_form page',
    }
    if request.method == 'POST':
        modelform=model_form(request.POST)
        if modelform.is_valid():
            modelform.save(commit=True)
            return redirect('crud')
    
    return render(request, 'model_form.html',context=context_dir)
    
    
def crud(request):
    context_dir={
        'info':info.objects.values()
    }
    return render(request, 'crud.html',context=context_dir)


def delete(request):
    id=request.GET.get('id')
    a=info.objects.get(id=id)
    a.delete()
    
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def update1(request):
    o=info.objects.get(id=request.GET.get('id'))
    updateform=update()
    context_dir={'form':updateform}
    if request.method == 'POST':
        updateform=update(request.POST)
        
        if updateform.is_valid():
            data=updateform.cleaned_data
            
            if len(data['name'])>0:
                o.name=data['name']
                o.save()
    
            if len(str(data['age']))>0:
                o.age=data['age']
                o.save()
                
            if len(data['gender'])>0:
                o.gender=data['gender']
                o.save()
        return HttpResponseRedirect('crud')
    
    return render(request, 'update.html',context=context_dir)

templates/basic_form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'crudapp.css' %}">
    <title>Document</title>
</head>
<body>
    <h1>{{page}}</h1>
    <h1>{{request}}</h1>
    <table>
        <tr>
            <th>
                Name
            </th>
            <th>Age</th>
            <th>Gender</th>
        </tr>
        {%for i in form1%}
        <tr>
            <h1>
               
                <td> {{i.name}}</td>
                <td> {{i.age}}</td>
                <td> {{i.gender}}</td>
        
            </h1>
        </tr>
        {%endfor%}
        </table>
    <div class="container" id="form_class">
    <form action="" method="post">
   <div>{{form.as_p}}</div>
    {%csrf_token%}
    <input type="submit" >
</form>
</div>
<div>
    {{form_details.name}}
    {{form_details.age}}
    {{form_details.gender}}
</div>

<div>
    {{all_data.name}}
    {{all_data.age}}
    {{all_data.gender}}
</div>
<div class="container" id="form_class">
    <form action="" method="POST">
        {%csrf_token%}
        Name:<input type="text" name="name">
        age:<input type="number" name="age">
        Gender:<input type="text" name="gender">
        <input type="submit" value="submit">
    </form>
</div>

<div>
    {{html_form_data.name}}
    {{html_form_data.age}}
    {{html_form_data.gender}}
</div>
</body>
</html>

templates/crud.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'crud.css' %}">
    <title>CRUD</title>
</head>
<body>
    <h1>This is example of CRUD app</h1>
    <div class="container ">
        <table class="ta" >
            <tr>
                <th>Name</th>
                <th>Age</th>
                <th>Gender</th>
                <th colspan="2">Action</th>
            </tr>
            {%for i in info%}
            <tr>
                <th>{{i.name}}</th>
                <th>{{i.age}}</th>
                <th>{{i.gender}}</th>
                <th> <a href="update?id={{i.id}}"> Update</a></th>
                <th><a href="delete?id={{i.id}}"> Delete</a></th>
            </tr>
            {%endfor%}
            <tr>
                <th colspan='5'> <a href="model_form"> Insert</a></th>
            </tr>
        </table>
    </div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'crudapp.css' %}">
    <title>Document</title>
</head>
<body>
    <h1>{{page}}</h1>
    <h1>{{request}}</h1>
    <table>
        <tr>
            <th>
                Name
            </th>
            <th>Age</th>
            <th>Gender</th>
        </tr>
        {%for i in form%}
        <tr>
            <h1>
               
                <td> {{i.name}}</td>
                <td> {{i.age}}</td>
                <td> {{i.gender}}</td>
        
            </h1>
        </tr>
        {%endfor%}
        </table>
        <a href="{% url 'crudapp:crud' %}"><button >CRUD</button></a>
</body>
</html>

templates/model_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>This is the example of model form</h1>
    <h1>{{page}}</h1>
    <h1>{{request}}</h1>
    <table>
        <tr>
            <th>
                Name
            </th>
            <th>Age</th>
            <th>Gender</th>
        </tr>
        {%for i in form%}
        <tr>
            <h1>
               
                <td> {{i.name}}</td>
                <td> {{i.age}}</td>
                <td> {{i.gender}}</td>
        
            </h1>
        </tr>
        {%endfor%}
        </table>
    <div class="container">
        <form action="" method="post">
            {{modelform.as_p}}
            {%csrf_token%}
            <input type="submit" value="submit">
        </form>
    </div>
</body>
</html>

templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update</title>
</head>
<body>
    <h1>
        H=Update record
    </h1>
<form action="" method="post">
    {{form.as_p}}
    {%csrf_token%}
    <input type="submit" value="Submit">
</form>
</body>
</html>